### PR TITLE
fix: reduce bundle size

### PR DESCRIPTION
**Pull request by hugomrdias**
This PR reduces the bundle size (OKR work)

53.27KB > 48.66KB  -8.64%

Needs
- [x] https://github.com/dignifiedquire/borc/pull/38
- [x] https://github.com/ipfs/aegir/pull/307

### CODE REVIEW

**Comment by hugomrdias** [comment]
removed async 
it needs to depend on those that borc and aegir make it smaller
can you review the aegir PR ?

**Comment by vmx** [comment]
@hugomrdias The updates from borc and aegir can then come through either implicit updates (likely for borc) or explicit upgrades (likely for aegir). So you wouldn't need to change this commit again.

Also those dependency updates are semi-automatic as Greenkeeper is enabled on this repo.

**Comment by hugomrdias** [comment]
its easier for me to have it like this so i dont forget anything and follow a path until a arrive at http-client and ipfs

**Comment by hugomrdias** [comment]
@vmx this is ready to merge/release

**Comment by hugomrdias** [comment]
@vmx this PR is synced with master

**Comment by vmx** [comment]
@hugomrdias GitHub tells me "This branch cannot be rebased due to conflicts".

**Pull request merged**
